create database UserDB;
use UserDB;
grant all on UserDB.* to 'admin'@'localhost' identified by 'test';
CREATE TABLE USER_INFO(
USERID INT(11) NOT NULL AUTO_INCREMENT,
FIRSTNAME VARCHAR(45) DEFAULT NULL,
LASTNAME VARCHAR(45) DEFAULT NULL,
DOB DATE DEFAULT NULL,
EMAIL VARCHAR(100) DEFAULT NULL,
PRIMARY KEY (USERID)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8